# --- THEME & COLORS ---
include themes/mocha.conf
background_opacity 0.85
dynamic_background_opacity yes

# --- TYPOGRAPHY ---
font_family      JetBrains Mono Nerd Font
font_size        12.0
disable_ligatures never

# --- CURSOR AESTHETICS ---
cursor_shape     beam
cursor_trail     1
cursor_trail_decay 0.1 0.4

# --- WINDOW & PADDING ---
window_padding_width 12
hide_window_decorations yes
confirm_os_window_close 0

# --- TABS (Powerline Style) ---
tab_bar_edge            top
tab_bar_style           powerline
tab_powerline_style     slanted
active_tab_font_style   bold
shell /bin/zsh
